
global:
  resolve_timeout: 1m   # How long to wait before resolving an alert
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'naveenykumar64@gmail.com'
  smtp_auth_username: 'naveenykumar64@gmail.com'
  smtp_auth_password: 'xxxx xxxx xxxx xxxx' # Use App Password for Gmail

route:
  receiver: "default" # Default receiver if no specific match is found
  # group_by: ['alertname', 'job'] # Groups alerts with the same alert name and job
  # group_wait: 30s # Wait time before sending the first notification
  # group_interval: 5m # Minimum wait time between grouped notifications
  repeat_interval: 3h # Repeats notifications every 3 hours for active alerts

  routes:
    # - matchers:
    #     - severity="critical" 
    #     # - team="devOps"
    #   receiver: "slack-urgent" # Route critical alerts to Slack
    - matchers:
        - team="devOps"
      receiver: "devops-email" # Route DevOps alerts to email

receivers:
  - name: "default"
    email_configs:
      - to: "naveenykumar64@gmail.com" # Default email for alerts
  # - name: "slack-urgent"
  #   slack_configs:
  #     - channel: "#alerts"
  #       send_resolved: true
  #       title: "{{ .CommonAnnotations.summary }}" # Use summary as the alert title
  #       text: "{{ .CommonAnnotations.description }}" # Detailed alert message
  - name: "devops-email"
    email_configs:
      - to: "naveenykumar64@gmail.com" # Send DevOps-related alerts here


# config/alertmanager.yml

# route:
#   receiver: 'null' # The default receiver
#   group_by: ['alertname', 'cluster', 'service']

# receivers:
# - name: 'null'