# version: '3.8'

networks:
  monitoring_net:
    driver: bridge

volumes:
  prometheus-data:
    driver : local
  grafana-storage: {}

services:
  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus-data:/promethues
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      # - '--config.file=/etc/prometheus/alert_rules.yml'
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring_net
    depends_on:
      - prometheus

  node-exporter:  
    image: prom/node-exporter:v1.8.0  # This will for windows docker desktop too
    container_name: node-exporter
    ports:
      - "9100:9100"
    # pid: host
    # volumes:
    #   - /:/host:ro,rslave
    #   - /proc:/host/proc:ro
    #   - /sys:/host/sys:ro
    # command:
    #   - '--path.rootfs=/host'
    #   - '--path.procfs=/host/proc'
    #   - '--path.sysfs=/host/sys'
    networks:
      - monitoring_net


  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./AlertManager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    # restart: unless-stopped


