name: Build and Push FastAPI Docker Image to ECR
on:
  push:
    branches:
      - main

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
#   AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}

defaults:
  run:
    working-directory: ./FastApi_simple_app

env:
  AWS_REGION: us-east-1


jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Configure AWS credentials using ACCESS KEYS
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      #     aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }}

      - name: Build, tag, and push Docker image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dev_ecr_repo
          IMAGE_TAG: v2
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

        